### ISSUE TITLE
Add a license to the code

### ISSUE THREAD

**Issue by CarVac** [obstruse/pico-composite8#2]
I'm interested in making a derivative of this code for a GPLv3 project of mine, but there is no license.

Would you mind putting it under either GPL3 or some more permissive license?

(I want to cut it down to only 3 bits but using a custom resistor ladder that still hits the sync voltage precisely)

**Comment by obstruse** [comment]
I cut it down to 4-bits for obstruse/life, and 2-bits for obstruse/lissajous.
GPL'd.

**Comment by CarVac** [comment]
Thanks so much!
