### ISSUE TITLE
Is there any possible to make analog video input (from FPV camera fo i.e.)?

### ISSUE THREAD

**Issue by NicholasShatokhin** [obstruse/pico-composite8#4]
Is it possible to make grayscale analog video input via gpio?

**Comment by obstruse** [comment]
Probably wouldn't work very well - the Pico ADC is 2 usec per sample.  That would give about a 25 pixel horizontal resolution.  Might be able to overclock to 50 pixels...

**Comment by NicholasShatokhin** [comment]
Can you tell how? I will use it as example with bigger raspberry pies.

Or can I use some external ADC?

**Comment by obstruse** [comment]
Probably the easiest would be to use a USB Video Capture Device.  They accept analog video input and present as a USB camera.  Plug that into a Raspberry Pi (3 or 4) and you can use Python:  PiCamera, OpenCV, etc...

(Looks like GitHub isn't forwarding messages?)

**Comment by NicholasShatokhin** [comment]
Too slow. I need realtime solution
